config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'questions#index'

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'devise_override/omniauth',
               confirmations: 'devise_override/confirmations',
               registrations: 'devise_override/registrations'
             }

  resources :questions do
    resources :answers, shallow: true do
      patch :make_best, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :votes, only: :create
    delete :votes, controller: :votes, action: :destroy
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, as: :commentable, dependent: :destroy
  has_one  :award, dependent: :destroy
  has_many_attached :files
  accepts_nested_attributes_for :award, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, except: %i[index new create]
  before_action :send_question_ids_to_front, only: :show
  after_action  :publish_question, only: :create

  def index
    @questions = Question.all
  end

  def new
    @question = current_user.questions.new
    @question.award = Award.new
    @question.links.build
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def show
    @answer = @question.answers.new
    @answer.links.build
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if @question.destroy
      redirect_to questions_path, notice: 'Your question was successfully removed.'
    else
      redirect_to @question
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question)
          .permit(:title, :body,
                  files: [],
                  links_attributes: %i[id title url _destroy],
                  award_attributes: %i[id title url _destroy])
  end

  def send_question_ids_to_front
    gon.question_id      = @question.id
    gon.question_creator = @question.user_id
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(json: @question)
    )
  end
end

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  = render 'awards/award_form', resource: f
  = render 'links/links_form', resource: f
  = f.submit :create

app/views/questions/_question.html.slim
.question id="question-#{@question.id}"
  h1= @question.title
  p= @question.body

  = render 'shared/vote', votable: @question

  #award
    - if @question.award
      = render @question.award

  .attachments
    = render partial: "attachments/attachment", collection: @question.files

  .links
    = render question.links

  - if can? :manage, @question
    = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = link_to 'Delete question', question_path(@question), method: :delete

  .question_errors
    = render 'shared/errors', resource: @question
  = form_with model: question, remote: true, class: 'hidden', html: {id: "edit-question-#{question.id}"}  do |f|
    = f.text_area :title
    = f.text_area :body, rows: 3
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/links_form', resource: f
    = f.submit 'Save'
  = render 'comments/index', commentable: @question

app/views/questions/_question_item.slim
p= link_to question.title, question

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
= react_component("QuestionsList", questions: @questions )

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
= render @question

= render 'answers/form'

= react_component("AnswersList", answers: @question.answers )

app/views/questions/update.js.erb
$('.question_errors').html("<%= render 'shared/errors', resource: @question %>");

<% if @question.errors.present? %>
  $('.notice').html("");
<% else %>
  $('.notice').html("Your question was successfully edited.");
  $('.question').html("<%= j render @question %>");
<% end %>