config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'questions#index'

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'devise_override/omniauth',
               confirmations: 'devise_override/confirmations',
               registrations: 'devise_override/registrations'
             }

  resources :questions do
    resources :answers, shallow: true do
      patch :make_best, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :votes, only: :create
    delete :votes, controller: :votes, action: :destroy
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource&.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_vote.html.slim
- if current_user && !current_user.author_of?(votable)
  .vote
    .rating
      = votable.rating
    = link_to '+1', api_votes_path(nil, vote: { votable_type: votable.class.to_s, votable_id: votable.id, value: 1 }), data: { votable_type: votable.class.to_s, votable_id: votable.id }, class: "vote-1-link #{votable.was_voted_by?(current_user) ? 'hidden' : ''}", method: :post, remote: true
    = link_to '-1', api_votes_path(nil, vote: { votable_type: votable.class.to_s, votable_id: votable.id, value: -1 }), data: { votable_type: votable.class.to_s, votable_id: votable.id }, class: "vote--1-link #{votable.was_voted_by?(current_user) ? 'hidden' : ''}", method: :post, remote: true
    = link_to 'unvote', api_votes_path(nil, vote: { votable_type: votable.class.to_s, votable_id: votable.id }), data: { votable_type: votable.class.to_s, votable_id: votable.id }, class: "unvote-link #{votable.was_voted_by?(current_user) ? '' : 'hidden'}", method: :delete, remote: true