config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'questions#index'

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'devise_override/omniauth',
               confirmations: 'devise_override/confirmations',
               registrations: 'devise_override/registrations'
             }

  resources :questions do
    resources :answers, shallow: true do
      patch :make_best, on: :member
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :votes, only: :create
    delete :votes, controller: :votes, action: :destroy
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable

  has_many :links, dependent: :destroy, as: :linkable
  has_many :comments, as: :commentable, dependent: :destroy

  has_many_attached :files

  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(best: :desc) }

  def make_best!
    transaction do
      question.answers.where.not(id: id).update_all(best: false)
      question.award&.update!(user: user)
      update!(best: true)
    end
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_answer, only: %i[update make_best destroy]
  after_action  :publish_answer, only: :create

  def create
    @question = Question.find(params[:question_id])
    @answer   = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params)
  end

  def make_best
    @answer.make_best!
    flash[:notice] = 'The answer was marked as best.'
    redirect_to @answer.question
  end

  def destroy
    @answer.destroy
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id title url _destroy])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}/answers",
      ApplicationController.render(json: @answer)
    )
  end
end

app/views/answers/_answer.html.slim
- if answer&.body&.present?
    .answer id="answer-#{answer.id}"
      .body
        = answer.body
      = render 'shared/vote', votable: answer
      .links
        =render answer.links
      .attachments
        = render partial: "attachments/attachment", collection: answer.files
      - if can? :make_best, answer
        - if answer.best?
          .best_answer_mark The best answer!
        - else
          = link_to 'Make best', make_best_answer_path(answer), class: 'make-best-answer-link', method: :patch, remote: true
      - if can? :update, answer
        = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      - if can? :delete, answer
        = link_to 'Delete answer', answer, remote: true, method: :delete
      = form_with model: answer, remote: true, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }  do |f|
        = f.text_area :body, rows: 3
        = f.label :files
        = f.file_field :files, multiple: true
        = render 'links/links_form', resource: f
        = f.submit 'Save'
      = render 'comments/index', commentable: answer

app/views/answers/_form.html.slim
- if current_user
  .answer_form
    .answer_errors
      = render 'shared/errors', resource: @answer
    = form_with model: [@question, @answer], remote: true do |f|
      = f.text_area :body, rows: 3
      = render 'links/links_form', resource: f
      = f.label :files
      = f.file_field :files, multiple: true
      = f.submit 'answer'

app/views/answers/create.js.erb
$('.answer_errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.notice').html("Your answer was successfully created.");
  $('#answers').append("<%= j render @answer %>");
  $('#answer_body').val("");
<% else %>
  $('.notice').html("");
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html("Your answer was successfully removed.");
$('<%= "#answer-#{@answer.id}" %>').remove();

app/views/answers/update.js.erb
$('.answer_errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.errors.present? %>
  $('.notice').html("");
<% else %>
  $('.notice').html("Your answer was successfully edited.");
  $('<%= "#answer-#{@answer.id}" %>').html("<%= j render @answer %>");
  $("form#edit-answer-<%= @answer.id %>").addClass('hidden');
<% end %>